export const ENDPOINT_LOGIN = '/login'
export const ENDPOINT_ESTUDIANTES = '/estudiantes'
export const ENDPOINT_CURSOS = '/cursos'
export const ENDPOINT_MATRICULAS = '/matriculas'
export const ENDPOINT_MENU = '/menus'