export const SET_AUTHENTICATED_START = 'SET_AUTHENTICATED_START'
export const SET_AUTHENTICATED_SUCCESS = 'SET_AUTHENTICATED_SUCCESS'
export const SET_AUTHENTICATED_FAIL = 'SET_AUTHENTICATED_FAIL'
export const SET_AUTHENTICATED_FINISH = 'SET_AUTHENTICATED_FINISH'

export const SET_MENU_START = 'SET_MENU_START'
export const SET_MENU_SUCCESS = 'SET_MENU_SUCCESS'
export const SET_MENU_FAIL = 'SET_MENU_FAIL'
export const SET_MENU_FINISH = 'SET_MENU_FINISH'

export const SIGN_OUT = 'SIGN_OUT'