export const GET_CURSOS_START = 'GET_CURSOS_START'
export const GET_CURSOS_SUCCESS = 'GET_CURSOS_SUCCESS'
export const GET_CURSOS_FAIL = 'GET_CURSOS_FAIL'
export const GET_CURSOS_FINISH = 'GET_CURSOS_FINISH'

export const DELETE_CURSO_START = 'DELETE_CURSO_START'
export const DELETE_CURSO_SUCCESS = 'DELETE_CURSO_SUCCESS'
export const DELETE_CURSO_FAIL = 'DELETE_CURSO_FAIL'
export const DELETE_CURSO_FINISH = 'DELETE_CURSO_FINISH'

export const ADD_CURSO_START = 'ADD_CURSO_START'
export const ADD_CURSO_SUCCESS = 'ADD_CURSO_SUCCESS'
export const ADD_CURSO_FAIL = 'ADD_CURSO_FAIL'
export const ADD_CURSO_FINISH = 'ADD_CURSO_FINISH'

export const EDIT_CURSO_START = 'EDIT_CURSO_START'
export const EDIT_CURSO_SUCCESS = 'EDIT_CURSO_SUCCESS'
export const EDIT_CURSO_FAIL = 'EDIT_CURSO_FAIL'
export const EDIT_CURSO_FINISH = 'EDIT_CURSO_FINISH'