export const GET_ESTUDIANTES_START = 'GET_ESTUDIANTES_START'
export const GET_ESTUDIANTES_SUCCESS = 'GET_ESTUDIANTES_SUCCESS'
export const GET_ESTUDIANTES_FAIL = 'GET_ESTUDIANTES_FAIL'
export const GET_ESTUDIANTES_FINISH = 'GET_ESTUDIANTES_FINISH'

export const DELETE_ESTUDIANTE_START = 'DELETE_ESTUDIANTE_START'
export const DELETE_ESTUDIANTE_SUCCESS = 'DELETE_ESTUDIANTE_SUCCESS'
export const DELETE_ESTUDIANTE_FAIL = 'DELETE_ESTUDIANTE_FAIL'
export const DELETE_ESTUDIANTE_FINISH = 'DELETE_ESTUDIANTE_FINISH'

export const ADD_ESTUDIANTE_START = 'ADD_ESTUDIANTE_START'
export const ADD_ESTUDIANTE_SUCCESS = 'ADD_ESTUDIANTE_SUCCESS'
export const ADD_ESTUDIANTE_FAIL = 'ADD_ESTUDIANTE_FAIL'
export const ADD_ESTUDIANTE_FINISH = 'ADD_ESTUDIANTE_FINISH'

export const EDIT_ESTUDIANTE_START = 'EDIT_ESTUDIANTE_START'
export const EDIT_ESTUDIANTE_SUCCESS = 'EDIT_ESTUDIANTE_SUCCESS'
export const EDIT_ESTUDIANTE_FAIL = 'EDIT_ESTUDIANTE_FAIL'
export const EDIT_ESTUDIANTE_FINISH = 'EDIT_ESTUDIANTE_FINISH'