export const GET_MATRICULAS_START = 'GET_MATRICULAS_START'
export const GET_MATRICULAS_SUCCESS = 'GET_MATRICULAS_SUCCESS'
export const GET_MATRICULAS_FAIL = 'GET_MATRICULAS_FAIL'
export const GET_MATRICULAS_FINISH = 'GET_MATRICULAS_FINISH'

export const GET_MATRICULAS_USER_START = 'GET_MATRICULAS_USER_START'
export const GET_MATRICULAS_USER_SUCCESS = 'GET_MATRICULAS_USER_SUCCESS'
export const GET_MATRICULAS_USER_FAIL = 'GET_MATRICULAS_USER_FAIL'
export const GET_MATRICULAS_USER_FINISH = 'GET_MATRICULAS_USER_FINISH'

export const CLEAR_MATRICULAS_USER = 'CLEAR_MATRICULAS_USER'


export const GET_MATRICULA_DETAIL_START = 'GET_MATRICULA_DETAIL_START'
export const GET_MATRICULA_DETAIL_SUCCESS = 'GET_MATRICULA_DETAIL_SUCCESS'
export const GET_MATRICULA_DETAIL_FAIL = 'GET_MATRICULA_DETAIL_FAIL'
export const GET_MATRICULA_DETAIL_FINISH = 'GET_MATRICULA_DETAIL_FINISH'

